services:
  bitcoind:
    container_name: "bitcoind"
    build: bitcoind
    restart: always
    volumes:
      - ./bitcoind/bitcoin_data:/root/.bitcoin
      - ./bitcoind/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      - bitcoin-network

  electrumx:
    container_name: electrumx
    build: ./electrumx
    volumes:
      - ./electrumx/electrumx_data:/data
    networks:
      - bitcoin-network
    ports:
      - 0.0.0.0:51234:51234 # Expose ElectrumX to host, access at localhost:51234:t
    environment:
      - ALLOW_ROOT=1
      - COST_SOFT_LIMIT=0 
      - COST_HARD_LIMIT=0 
      - COIN=Bitcoin
      - NET=mutinynet
      - SERVICES=tcp://:51001,rpc:// 
      - DAEMON_URL=http://bitcoin:bitcoin@bitcoind:38332 # Using container name
      - DB_DIRECTORY=/data
      - DAEMON_POLL_INTERVAL_BLOCKS=100 
      - DAEMON_POLL_INTERVAL_MEMPOOL=100 
      - PEER_ANNOUNCE=1
    depends_on:
      - bitcoind
    restart: always

networks:
  bitcoin-network:
    driver: bridge
